<?php

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return json_decode('
{
    "_default": [
        "USPS",
        "UPS",
        "FedEx",
        "DHL"
    ],
    "bigcommerce": [
        "DHL"
    ],
    "bluefly": [
        "17 Post Service",
        "2GO",
        "360 Lion Express",
        "4-72 Entregando",
        "4PX",
        "ABF Freight",
        "ABX Express",
        "ACS Courier",
        "Adicional Logistics",
        "ADSOne",
        "AIR21",
        "Airpak Express",
        "Airspeed International Corporation",
        "alphaFAST",
        "An Post",
        "APC Overnight",
        "APC Overnight Reference",
        "APC Postal Logistics",
        "Aramex",
        "Arrow XL",
        "Asendia Germany",
        "Asendia HK (LATAM)",
        "Asendia UK",
        "Asendia USA",
        "ASM",
        "AuPost China",
        "Australia Post",
        "Austrian Post (Express)",
        "Austrian Post (Registered)",
        "B2C Europe",
        "Belgium Post",
        "Belpost",
        "Bert Transport",
        "Best Express",
        "Bluedart",
        "Bonds Couriers",
        "BOXC",
        "bpost international",
        "Brazil Correios",
        "BRT Bartolini",
        "Bulgarian Posts",
        "Buylogic",
        "Cambodia Post",
        "Canada Post",
        "Canpar Courier",
        "CBL Logistics",
        "China EMS",
        "China Post",
        "Chronopost France",
        "Chronopost Portugal",
        "City-Link Express",
        "CJ GLS",
        "CNE Express",
        "Colis Priv’©",
        "Colissimo",
        "Collect+",
        "Con-way Freight",
        "Correo Argentino",
        "Correos Chile",
        "Correos de Espa’±a",
        "Correos de Mexico",
        "Correos Express",
        "Cosmetics Now",
        "Courex",
        "Courier IT",
        "Courier Plus",
        "CourierPost",
        "Couriers Please",
        "cPacket",
        "Cuckoo Express",
        "Cyprus Post",
        "DACHSER",
        "Dawn Wing",
        "DB Schenker Sweden",
        "Delcart",
        "Delhivery",
        "Deltec Courier",
        "Detrack",
        "Deutsche Post DHL",
        "Deutsche Post Mail",
        "DHL 2-Mann-Handling",
        "DHL Benelux",
        "DHL eCommerce",
        "DHL Express",
        "DHL Express (Piece ID)",
        "DHL Global Mail Asia",
        "DHL Hong Kong",
        "DHL Netherlands",
        "DHL Parcel NL",
        "DHL Poland Domestic",
        "DHL Spain Domestic",
        "Direct Freight Express",
        "Direct Link",
        "DMM Network",
        "Dotzot",
        "DPD",
        "DPD Germany",
        "DPD Ireland",
        "DPD Poland",
        "DPD UK",
        "DPE Express",
        "DPE South Africa",
        "DPEX",
        "DPEX China",
        "DSV",
        "DTDC Australia",
        "DTDC India",
        "DX",
        "Dynamic Logistics",
        "Easy Mail",
        "EC-Firstclass",
        "Ecargo",
        "Echo",
        "Ecom Express",
        "ELTA Hellenic Post",
        "Emirates Post",
        "EMPS Express",
        "Ensenda",
        "Envialia",
        "Equick China",
        "Estafeta",
        "Estes",
        "Exapaq",
        "Expeditors",
        "Fastrak Services",
        "Fastway Australia",
        "Fastway Ireland",
        "Fastway New Zealand",
        "Fastway South Africa",
        "FedEx",
        "FedEx Freight",
        "FedEx Poland Domestic",
        "FedEx UK",
        "FERCAM Logistics & Transport",
        "First Flight Couriers",
        "First Logistics",
        "Flyt Express",
        "Gati-KWE",
        "GDEX",
        "Geniki Taxydromiki",
        "GEODIS - Distribution & Express",
        "Giao h’¾ng nhanh",
        "Globegistics Inc.",
        "GLS",
        "GLS Italy",
        "GLS Netherlands",
        "GoFly",
        "GoJavas",
        "Greyhound",
        "Hermes Germany",
        "Hermesworld",
        "Homedirect Logistics",
        "Hong Kong Post",
        "Hrvatska Pota",
        "Hua Han Logistics",
        "i-parcel",
        "Iceland Post",
        "IDEX",
        "IMEX Global Solutions",
        "IMX Mail",
        "India Post Domestic",
        "India Post International",
        "InPost Paczkomaty",
        "Interlink Express",
        "International Seur",
        "Israel Post",
        "Israel Post Domestic",
        "Italy SDA",
        "ITIS International",
        "Jam Express",
        "Japan Post",
        "Jayon Express (JEX)",
        "JCEX",
        "Jet-Ship Worldwide",
        "JNE",
        "JP BH Pota",
        "Kangaroo Worldwide Express",
        "Kerry Express Thailand",
        "Kerry TTC Express",
        "KGM Hub",
        "Korea Post",
        "Kuehne + Nagel",
        "La Poste",
        "Lao Post",
        "LaserShip",
        "LBC Express",
        "Lietuvos Patas",
        "Lion Parcel",
        "Logistic Worldwide Express",
        "Magyar Posta",
        "Malaysia Post - Registered",
        "Malaysia Post EMS / Poslaju",
        "Matdespatch",
        "Matkahuolto",
        "Maxcellents Pte Ltd",
        "Mexico AeroFlash",
        "Mexico Redpack",
        "Mexico Senda Express",
        "Mondial Relay",
        "MRW",
        "myHermes UK",
        "Mypostonline",
        "NACEX Spain",
        "Nanjing Woyuan",
        "Nationwide Express",
        "New Zealand Post",
        "Newgistics",
        "Nexive (TNT Post Italy)",
        "Nhans Solutions",
        "Nightline",
        "Ninja Van",
        "Ninja Van Indonesia",
        "Ninja Van Malaysia",
        "NiPost",
        "Norsk Global",
        "Nova Poshta",
        "NuvoEx",
        "OCA Argentina",
        "Old Dominion Freight Line",
        "Omni Parcel",
        "One World Express",
        "OnTrac",
        "ó‘esk’ Pota",
        "Packlink",
        "Pandu Logistics",
        "Panther",
        "Parcel Express",
        "Parcel Force",
        "Parcel Post Singapore",
        "Parcelled.in",
        "PayPal Package",
        "PFC Express",
        "Poczta Polska",
        "Portugal CTT",
        "Portugal Seur",
        "Pos Indonesia Domestic",
        "Pos Indonesia Int\'l",
        "Post Danmark",
        "Post Serbia",
        "Post56",
        "Poste Italiane",
        "Poste Italiane Paccocelere",
        "Posten Norge / Bring",
        "Posti",
        "PostNL Domestic",
        "PostNL International",
        "PostNL International 3S",
        "PostNord Logistics",
        "Professional Couriers",
        "PTT Posta",
        "Purolator",
        "Quantium",
        "Qxpress",
        "Raben Group",
        "RAF Philippines",
        "RaidereX",
        "RAM",
        "Red Express",
        "Red Express Waybill",
        "Redur Spain",
        "RL Carriers",
        "Rocket Parcel International",
        "Royal Mail",
        "RPX Indonesia",
        "RPX Online",
        "RR Donnelley",
        "Russian Post",
        "RZY Express",
        "S.F International",
        "S.F. Express",
        "Safexpress",
        "Sagawa",
        "Saudi Post",
        "Scudex Express",
        "SEKO Logistics",
        "SFC Service",
        "SGT Corriere Espresso",
        "Singapore Post",
        "Singapore Speedpost",
        "Siodemka",
        "SkyNet Malaysia",
        "SkyNet Worldwide Express",
        "Skynet Worldwide Express UK",
        "SMSA Express",
        "South African Post Office",
        "Spanish Seur",
        "Specialised Freight",
        "Speed Couriers",
        "Speedex Courier",
        "Spreadel",
        "SRE Korea",
        "Star Track Express",
        "StarTrack",
        "STO Express",
        "Sweden Posten",
        "Swiss Post",
        "Taiwan Post",
        "TAQBIN Hong Kong",
        "TAQBIN Malaysia",
        "TAQBIN Singapore",
        "Teliway SIC Express",
        "TGX",
        "Thailand Thai Post",
        "The Courier Guy",
        "Tiki",
        "TNT",
        "TNT Australia",
        "TNT France",
        "TNT Italy",
        "TNT Reference",
        "TNT UK",
        "TNT UK Reference",
        "TNT-Click Italy",
        "Toll IPEC",
        "Toll Priority",
        "TrakPak",
        "TransMission",
        "Tuffnells Parcels Express",
        "UBI Logistics Australia",
        "UK Mail",
        "UkrPoshta",
        "UPS",
        "UPS Freight",
        "UPS Mail Innovations",
        "USPS",
        "Vietnam Post",
        "Vietnam Post EMS",
        "ViettelPost",
        "Wahana",
        "WeDo Logistics",
        "WishPost",
        "XDP Express",
        "XDP Express Reference",
        "Xend Express",
        "XpressBees",
        "XQ Express",
        "Yamato Japan",
        "Yanwen",
        "Yodel Domestic",
        "Yodel International",
        "YRC",
        "YTO Express",
        "Yun Express",
        "Yunda Express",
        "Zalora 7-Eleven",
        "ZJS International"
    ],
    "custom": [
        "UPS",
        "FedEx",
        "DHL"
    ],
    "ebay": [
        "UPS",
        "USPS",
        "FedEx",
        "DHL"
    ],
    "etsy": [
        "4PX Worldwide Express",
        "ABF Freight",
        "ACS Courier",
        "AeroFlash",
        "Afghan Post",
        "An Post",
        "Anguilla Postal Service",
        "APC Postal Logistics",
        "Aramex",
        "Asendia UK",
        "Asendia USA",
        "Australia Post",
        "Austrian Post",
        "Austrian Post Registered",
        "Bahrain Post",
        "Bangladesh Post Office",
        "Belgium Post Domestic",
        "Belgium Post International",
        "Belposhta",
        "BH Posta",
        "Blue Dart",
        "BotswanaPost",
        "Brunei Postal Services",
        "Bulgarian Posts",
        "Cambodia Post",
        "Canada Post",
        "Canpar Courier",
        "Ceska Posta",
        "China EMS",
        "China Post",
        "Chit Chats",
        "Chronopost France",
        "Chronopost Portugal",
        "Chunghwa Post",
        "City Link",
        "Colissimo",
        "Collect+",
        "Correios de Brasil",
        "Correios de Macau",
        "Correios de Portugal (CTT)",
        "Correo Argentino Domestic",
        "Correo Argentino International",
        "Correo Uruguayo",
        "Correos - Espana",
        "Correos Chile",
        "Correos de Costa Rica",
        "Correos De Mexico",
        "Correos del Ecuador",
        "Courier Post",
        "Couriers Please",
        "Cyprus Post",
        "Deltec Courier",
        "Deutsche Post",
        "DHL Benelux",
        "DHL Express",
        "DHL Germany",
        "DHL Global Mail",
        "DHL Global Mail Asia",
        "DHL Netherlands",
        "DHL Parcel NL",
        "DHL Polska",
        "DHL Spain Domestic",
        "Direct Link",
        "DPD",
        "DPD Germany",
        "DPD Polska",
        "DPD UK",
        "DTDC India",
        "EC-Firstclass",
        "Egypt Post",
        "El Correo",
        "Elta Courier",
        "Empost",
        "Empresa de Correos de Bolivia",
        "Estafeta",
        "Estes",
        "Estonian Post",
        "Ethiopian Postal Service",
        "Evergreen",
        "Fastway Australia",
        "Fastway Couriers",
        "Fastway New Zealand",
        "Fastways Couriers South Africa",
        "FedEx",
        "Fedex UK (Domestic)",
        "First Flight Couriers",
        "Flash Courier",
        "GATI-KWE",
        "Ghana Post",
        "Globegistics",
        "GLS",
        "Greyhound",
        "Guernsey Post",
        "Hay Post",
        "Hellenic Post",
        "Hermes",
        "Hermes Germany",
        "Hermes Italy",
        "Hong Kong Post",
        "Hrvatska Posta",
        "i-parcel",
        "India Post",
        "India Post International",
        "Interlink Express",
        "International Seur",
        "Ipostel",
        "Iran Post",
        "Islandspostur",
        "Isle of Man Post Office",
        "Israel Post",
        "Israel Post Domestic",
        "Jamaica Post",
        "Japan Post",
        "Jersey Post",
        "Jordan Post",
        "Kazpost",
        "Korea Post",
        "Korea Post EMS",
        "Kuehne + Nagel",
        "La Poste",
        "La Poste du Senegal",
        "La Poste Monaco",
        "La Poste Tunisienne",
        "Landmark Global",
        "LaserShip",
        "Latvijas Pasts",
        "LibanPost",
        "Lietuvos Pastas",
        "Magyar Posta",
        "Makedonska Posta",
        "Malaysia Pos Daftar",
        "Maldives Post",
        "MaltaPost",
        "Mauritius Post",
        "Mondial Relay",
        "MRW",
        "Multipack",
        "myHermes UK",
        "Nacex",
        "New Zealand Post",
        "Nexive",
        "Nieuwe Post Nederlandse Antillen (PNA)",
        "Nigerian Postal Service",
        "Nova Poshta",
        "OCA",
        "Oman Post",
        "OnTrac",
        "OPEK",
        "OPT",
        "OPT de Nouvelle-Caledonie",
        "Pakistan Post",
        "Parcelforce Worldwide",
        "Poczta Polska",
        "Pos Indonesia",
        "Pos Indonesia International",
        "Pos Malaysia",
        "Post Aruba",
        "Post Fiji",
        "Post Luxembourg",
        "Posta",
        "Posta Kenya",
        "Posta Moldovei",
        "Posta Romana",
        "Posta Shqiptare",
        "Posta Slovenije",
        "Posta Srbije",
        "Posta Uganda",
        "Poste Italiane",
        "Poste Italiane Paccocelere",
        "Poste Maroc",
        "Posten AB",
        "Posten Norge",
        "Posti",
        "Postmates",
        "PostNL Domestic",
        "PostNL International",
        "PostNL International 3S",
        "PostNord",
        "PostNord Logistics",
        "PTT Posta",
        "Purolator",
        "Qatar Post",
        "Red Express",
        "Redpack",
        "RL Carriers",
        "Royal Mail",
        "RPX Indonesia",
        "Russian Post",
        "S.F International",
        "Safexpress",
        "Sagawa",
        "Saudi Post",
        "SDA Express Courier",
        "Selektvracht",
        "Senda Express",
        "Sendle",
        "Serpost",
        "SEUR Espana (Domestico)",
        "SEUR Portugal (Domestico)",
        "SF Express",
        "Singapore Post",
        "Singapore SpeedPost",
        "Siodemka",
        "Skynet Malaysia",
        "SkyNet Wordwide Express",
        "Skynet Worldwide Express",
        "Slovenska posta",
        "South Africa Post Office",
        "StarTrack",
        "Swiss Post",
        "TA-Q-BIN Hong Kong",
        "TA-Q-BIN Japan",
        "TA-Q-BIN Malaysia",
        "TA-Q-BIN Singapore",
        "TGX",
        "Thailand Post",
        "TNT",
        "TNT Australia",
        "TNT France",
        "TNT Italia",
        "TNT UK",
        "Toll Global Express",
        "Toll Priority",
        "TTPost",
        "UK Mail",
        "UkrPoshta",
        "UPS",
        "UPS Freight",
        "USPS",
        "Vanuatu Post",
        "Vietnam Post",
        "Vietnam Post EMS",
        "Whistl",
        "Xend",
        "Yanwen",
        "Yemen Post",
        "Yodel",
        "Yodel International",
        "YRC Freight",
        "Zampost",
        "Zimpost"
    ],
    "fba": [
        "UPS",
        "USPS",
        "FedEx",
        "DHL"
    ],
    "fbm": [
        "UPS",
        "USPS",
        "FedEx",
        "DHL"
    ],
    "googleexpress": [
        "GSX",
        "UPS",
        "USPS",
        "FedEx",
        "DHL",
        "ECourier",
        "CXT",
        "Google",
        "OnTrac",
        "Emsy",
        "ONT",
        "Deliv",
        "Dynamex",
        "Lasership",
        "MPX",
        "UDS"
    ],
    "opencart": [
        "USPS",
        "UPS",
        "usps.00",
        "usps.1",
        "ups.03",
        "usps.15",
        "FedEx"
    ],
    "overstock": [
        "7LSP",
        "AAA",
        "ABF",
        "ACE",
        "AIT",
        "ALG",
        "AMTRUCK",
        "AMWST",
        "ASAQ",
        "AVERITT",
        "BKNS",
        "BULLET",
        "CANPOST",
        "CENF",
        "CEVA",
        "CNWY",
        "CRST",
        "CUSTOM",
        "DAFG",
        "DHL",
        "DHLGLOBL",
        "DMRG",
        "DOHRN",
        "DU",
        "EFWW",
        "ENSENDA",
        "EXLA",
        "FDEG",
        "FEDEX",
        "FEDSP",
        "FMHD",
        "FTFT",
        "FXFE",
        "GLBS",
        "HDUSA",
        "HEPD",
        "JBHT",
        "LDSO",
        "LSOV",
        "LTL",
        "MAIN",
        "MANNA",
        "METR",
        "MFSY",
        "MLRY",
        "MYFLWER",
        "NDLV",
        "NEMF",
        "NHHF",
        "NMTRAN",
        "OAKH",
        "ODFL",
        "OFFD",
        "OLTL",
        "ONTRAC",
        "OVNT",
        "PENN",
        "PILOT",
        "PITD",
        "PURLATOR",
        "RETL",
        "RL",
        "RRUN",
        "SAIA",
        "SEFL",
        "SEKO",
        "SPEEDEE",
        "TEGY",
        "TELE",
        "TRAIL",
        "TWW",
        "UPGF",
        "UPS",
        "UPSHG",
        "UPSMI",
        "UPSSP",
        "USPS",
        "USPSC",
        "USPSFC",
        "USPSY",
        "VITR",
        "VSXP",
        "WATK",
        "WTVA",
        "XPOL",
        "XPOY",
        "YELL",
        "YFLG",
        "YRC",
        "YUN"
    ],
    "shopify": [
        "A Duie Pyle",
        "A&M Trucking",
        "A1",
        "ABF",
        "APEX",
        "Averitt",
        "Bekins / Home Direct",
        "Cagney Global",
        "CEVA",
        "Delivered by Walmart",
        "DHL",
        "DHL Global Mail",
        "Dynamex",
        "Eastern Connection",
        "Ensenda",
        "Estes",
        "FedEx",
        "FedEx Freight",
        "FedEx SmartPost",
        "GSO",
        "Land Air Express",
        "Laser Ship",
        "Lone Star",
        "Mail Express",
        "Meyer",
        "MPX",
        "New Penn",
        "Newgistics",
        "NonstopDelivery",
        "Old Dominion",
        "OnTrac",
        "OnTrac Direct Post",
        "Other",
        "Parcel",
        "Pilot",
        "Prestige",
        "RBF",
        "Reddaway",
        "RL Carriers",
        "Roadrunner",
        "SAIA Freight",
        "Seko Worldwide",
        "Simmons Carrier",
        "Southeastern Freight",
        "Spee Dee",
        "UDS",
        "UES",
        "UPS",
        "UPS Freight",
        "UPS Mail Innovations",
        "UPS SurePost",
        "USPS",
        "YRC"
    ],
    "walmart": [
        "UPS",
        "USPS",
        "UPSMI",
        "FedEx",
        "Airborne",
        "OnTrac",
        "DHL",
        "NG",
        "LS",
        "FDX",
        "UDS"
    ],
    "walmartca": [
        "DHL",
        "UPS",
        "USPS",
        "UPSMI",
        "FedEx",
        "Airborne",
        "OnTrac",
        "NG",
        "LS",
        "FDX",
        "UDS",
        "CanPar"
    ],
    "walmartdsv": [
        "UPS Ground - DSV",
        "UPS Ground - S2S",
        "FedEx Home Delivery",
        "FedEx Ground - S2S",
        "FedEx Ground",
        "FedEx 2Day - S2S",
        "UPS Second Day Air - S2S",
        "FedEx 2Day",
        "FedEx Ground (Residential over 70 lbs)",
        "FedEx 3 Day (Upgrade)",
        "UPS Second day Air",
        "Pilot Freight Basic Delivery",
        "USPS Priority Mail",
        "Estes Forwarding Worldwide Basic Delivery",
        "FedEx Home Delivery no SDR",
        "UPS",
        "USPS",
        "UPSMI",
        "FedEx",
        "Airborne",
        "OnTrac",
        "NG",
        "LS",
        "FDX",
        "UDS"
    ],
    "wayfair": [
        "FedEx",
        "UPS"
    ],
    "woocommerce": [
        "USPS",
        "UPS",
        "FedEx",
        "DHL"
    ]
}
', true);
